import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import axiosInstance from '../utils/axiosInstance';
import { 
  Sparkles, 
  Copy, 
  Check, 
  Trash2, 
  Eye,
  Plus,
  ArrowLeft,
  LayoutGrid,
  ChevronDown,
  FileText,
  User,
  LogOut
} from 'lucide-react';
import { ProfileModal } from '../components/ProfileModal';

const CoverLetterPage = () => {
  const navigate = useNavigate();
  const { user, logout } = useAuth();
  const [profileDropdownOpen, setProfileDropdownOpen] = useState(false);
  const [isProfileOpen, setIsProfileOpen] = useState(false);

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  // Cover Letter Data State
  const [letters, setLetters] = useState([]);
  const [viewingLetter, setViewingLetter] = useState(null); // Active letter being viewed
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(false);

  // Form Input States
  const [companyName, setCompanyName] = useState('');
  const [jobTitle, setJobTitle] = useState('');
  const [jobDescription, setJobDescription] = useState('');

  // Page Flow States
  const [showCreate, setShowCreate] = useState(false); // Creating a new cover letter
  const [toolsDropdownOpen, setToolsDropdownOpen] = useState(false);

  // Alert & Clipboard States
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [copied, setCopied] = useState(false);

  // Fetch past cover letters
  const fetchLetters = async () => {
    try {
      setLoading(true);
      setError('');
      const res = await axiosInstance.get('/coverletter');
      setLetters(res.data);
    } catch (err) {
      console.error(err);
      setError('Could not fetch past cover letters.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLetters();
  }, []);

  // Generate Letter
  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!companyName || !jobTitle) return;

    setActionLoading(true);
    setError('');
    setSuccess('');
    
    try {
      const res = await axiosInstance.post('/coverletter/generate', {
        companyName,
        jobTitle,
        jobDescription,
      });
      setLetters(prev => [res.data, ...prev]);
      setViewingLetter(res.data);
      setShowCreate(false);
      setSuccess('Cover letter generated by AI!');
      
      // Clear form inputs
      setCompanyName('');
      setJobTitle('');
      setJobDescription('');
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.message || 'Failed to generate cover letter.');
    } finally {
      setActionLoading(false);
    }
  };

  // Delete Letter
  const handleDelete = async (id) => {
    if (!window.confirm('Delete this cover letter?')) return;
    try {
      setError('');
      await axiosInstance.delete(`/coverletter/${id}`);
      const filtered = letters.filter(l => l._id !== id);
      setLetters(filtered);
      if (viewingLetter?._id === id) {
        setViewingLetter(null);
      }
      setSuccess('Removed cover letter.');
    } catch (err) {
      console.error(err);
      setError('Failed to remove letter.');
    }
  };

  // Copy to clipboard
  const handleCopy = () => {
    if (!viewingLetter) return;
    navigator.clipboard.writeText(viewingLetter.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Format date helper (e.g. Created January 26th, 2025)
  const formatDate = (dateStr) => {
    try {
      const d = new Date(dateStr);
      const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
      const month = months[d.getMonth()];
      const year = d.getFullYear();
      const day = d.getDate();
      
      // Get ordinal suffix (st, nd, rd, th)
      const suffix = ["th", "st", "nd", "rd"][day % 10 > 3 || Math.floor(day % 100 / 10) === 1 ? 0 : day % 10];
      return `Created ${month} ${day}${suffix}, ${year}`;
    } catch (e) {
      return dateStr;
    }
  };

  return (
    <div className="min-h-screen bg-black text-foreground flex flex-col font-sans selection:bg-indigo-500/20">
      
      {/* Grid Pattern Overlay */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#12121c_1px,transparent_1px),linear-gradient(to_bottom,#12121c_1px,transparent_1px)] bg-[size:4rem_4rem] pointer-events-none opacity-40"></div>

      {/* Top Header Navbar */}
      <header className="sticky top-0 z-50 w-full border-b border-neutral-800/80 bg-black/80 backdrop-blur">
        <div className="container mx-auto px-6 h-16 flex items-center justify-between">
          
          {/* Logo SENSAi */}
          <Link to="/" className="font-sans tracking-tight text-white select-none text-xl font-extrabold">
            SENS<span>A</span><span className="text-blue-500 lowercase">i</span>
          </Link>

          {/* Right Header Controls */}
          <div className="flex items-center gap-4">
            <Link 
              to="/dashboard"
              className="bg-neutral-900 border border-neutral-800 text-neutral-200 hover:text-white px-3.5 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all duration-200"
            >
              <LayoutGrid className="w-3.5 h-3.5" />
              <span>Industry Insights</span>
            </Link>

            <div className="relative">
              <button 
                onClick={() => setToolsDropdownOpen(!toolsDropdownOpen)}
                className="bg-white hover:bg-neutral-100 text-black px-3.5 py-1.5 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all duration-200"
              >
                <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                <span>Growth Tools</span>
                <ChevronDown className="w-3 h-3 text-neutral-500" />
              </button>
              
              {toolsDropdownOpen && (
                <div className="absolute right-0 mt-2 w-48 bg-neutral-950 border border-neutral-800 rounded-lg shadow-xl py-1 z-50">
                  <Link 
                    to="/resume" 
                    onClick={() => setToolsDropdownOpen(false)}
                    className="block px-4 py-2 text-xs text-neutral-300 hover:bg-neutral-900 hover:text-white transition-all flex items-center gap-2"
                  >
                    <FileText className="w-3.5 h-3.5" />
                    Build Resume
                  </Link>
                  <Link 
                    to="/cover-letter" 
                    onClick={() => setToolsDropdownOpen(false)}
                    className="block px-4 py-2 text-xs text-neutral-300 hover:bg-neutral-900 hover:text-white transition-all flex items-center gap-2"
                  >
                    <FileText className="w-3.5 h-3.5" />
                    Cover Letter
                  </Link>
                  <Link 
                    to="/interview" 
                    onClick={() => setToolsDropdownOpen(false)}
                    className="block px-4 py-2 text-xs text-neutral-300 hover:bg-neutral-900 hover:text-white transition-all flex items-center gap-2"
                  >
                    <FileText className="w-3.5 h-3.5" />
                    Interview Prep
                  </Link>
                </div>
              )}
            </div>

            <div className="relative">
              <button 
                onClick={() => setProfileDropdownOpen(!profileDropdownOpen)}
                className="w-8 h-8 rounded-full border border-neutral-700 bg-neutral-800 flex items-center justify-center overflow-hidden hover:border-neutral-500 transition-all duration-200 text-xs font-bold text-white uppercase select-none"
              >
                {user?.imageUrl ? (
                  <img 
                    src={user.imageUrl}
                    alt="Profile"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <span>{user?.name?.charAt(0) || 'U'}</span>
                )}
              </button>

              {profileDropdownOpen && (
                <div className="absolute right-0 mt-2 w-56 bg-neutral-950 border border-neutral-800 rounded-lg shadow-xl py-1 z-50">
                  {user && (
                    <div className="px-4 py-2 border-b border-neutral-900">
                      <p className="text-xs font-bold text-white truncate">{user.name}</p>
                      <p className="text-[10px] text-neutral-500 truncate">{user.email}</p>
                    </div>
                  )}
                  <button 
                    onClick={() => { setProfileDropdownOpen(false); setIsProfileOpen(true); }}
                    className="w-full text-left block px-4 py-2 text-xs text-neutral-300 hover:bg-neutral-900 hover:text-white transition-all flex items-center gap-2 cursor-pointer"
                  >
                    <User className="w-3.5 h-3.5 animate-pulse text-indigo-400" />
                    Complete Profile
                  </button>
                  <button 
                    onClick={handleLogout}
                    className="w-full text-left px-4 py-2 text-xs text-red-450 hover:bg-neutral-900 hover:text-red-300 transition-all flex items-center gap-2"
                  >
                    <LogOut className="w-3.5 h-3.5" />
                    Logout
                  </button>
                </div>
              )}
            </div>
          </div>

        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 container mx-auto px-6 py-10 relative z-10 space-y-6 max-w-5xl">
        
        {/* Error notification banner */}
        {error && (
          <div className="p-4 bg-destructive/10 border border-destructive/20 rounded-lg text-xs text-red-400">
            {error}
          </div>
        )}

        {/* Success notification banner */}
        {success && (
          <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-lg text-xs text-emerald-400">
            {success}
          </div>
        )}

        {/* VIEW 1: Cover Letters List */}
        {!showCreate && !viewingLetter && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <h1 className="text-4xl font-extrabold text-white tracking-tight">My Cover Letters</h1>
              <button
                onClick={() => setShowCreate(true)}
                className="bg-white hover:bg-neutral-100 text-black px-4 py-2 rounded-lg text-xs font-bold transition-all flex items-center gap-1"
              >
                <Plus className="w-4 h-4 text-black" />
                <span>Create New</span>
              </button>
            </div>

            {/* List stacked cards */}
            <div className="space-y-4 pt-2">
              {loading ? (
                <div className="flex items-center justify-center py-20">
                  <div className="w-8 h-8 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                </div>
              ) : letters.length === 0 ? (
                <div className="text-center py-20 text-xs text-neutral-500 font-semibold border border-neutral-900 rounded-xl bg-[#09090b]">
                  No cover letters created yet. Click 'Create New' to build one!
                </div>
              ) : (
                letters.map((letter) => (
                  <div
                    key={letter._id}
                    className="p-6 border border-neutral-900 bg-[#09090b] rounded-xl flex items-center justify-between transition-all hover:border-neutral-850"
                  >
                    <div className="space-y-1">
                      <h3 className="font-bold text-white text-base">
                        {letter.companyName ? `${letter.jobTitle} at ${letter.companyName}` : letter.jobTitle}
                      </h3>
                      <p className="text-[10px] text-neutral-500 font-semibold">{formatDate(letter.createdAt)}</p>
                      <p className="text-xs text-neutral-400 font-bold mt-1.5 block">{letter.jobTitle}</p>
                    </div>

                    <div className="flex items-center gap-2.5">
                      <button
                        onClick={() => setViewingLetter(letter)}
                        className="p-2 border border-neutral-850 hover:border-neutral-700 bg-[#060608] text-neutral-400 hover:text-white rounded-lg transition-all"
                        title="View Letter"
                      >
                        <Eye className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(letter._id)}
                        className="p-2 border border-neutral-850 hover:border-neutral-700 bg-[#060608] text-neutral-400 hover:text-red-400 rounded-lg transition-all"
                        title="Delete Letter"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        {/* VIEW 2: Create Cover Letter Form */}
        {showCreate && (
          <div className="space-y-4">
            <button
              onClick={() => setShowCreate(false)}
              className="inline-flex items-center gap-1.5 text-xs text-neutral-400 hover:text-white font-semibold mb-2"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Cover Letters</span>
            </button>

            <div>
              <h1 className="text-4xl font-extrabold text-white tracking-tight">Create Cover Letter</h1>
              <p className="text-xs text-neutral-500 mt-1">Generate a tailored cover letter for your job application</p>
            </div>

            <div className="p-6 rounded-xl border border-neutral-900 bg-[#09090b] space-y-6">
              <div>
                <h3 className="font-bold text-white text-sm">Job Details</h3>
                <p className="text-[10px] text-neutral-500 mt-0.5">Provide information about the position you're applying for</p>
              </div>

              <form onSubmit={handleGenerate} className="space-y-5">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-neutral-400">Company Name</label>
                    <input
                      type="text"
                      required
                      value={companyName}
                      onChange={(e) => setCompanyName(e.target.value)}
                      placeholder="Enter company name"
                      className="block w-full px-3 py-2 bg-[#060608] border border-neutral-900 rounded-lg focus:outline-none focus:border-indigo-500 text-white text-xs"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-neutral-400">Job Title</label>
                    <input
                      type="text"
                      required
                      value={jobTitle}
                      onChange={(e) => setJobTitle(e.target.value)}
                      placeholder="Enter job title"
                      className="block w-full px-3 py-2 bg-[#060608] border border-neutral-900 rounded-lg focus:outline-none focus:border-indigo-500 text-white text-xs"
                    />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-neutral-400">Job Description</label>
                  <textarea
                    required
                    rows="8"
                    value={jobDescription}
                    onChange={(e) => setJobDescription(e.target.value)}
                    placeholder="Paste the job description here"
                    className="block w-full p-3 bg-[#060608] border border-neutral-900 rounded-lg focus:outline-none focus:border-indigo-500 text-white text-xs leading-relaxed"
                  />
                </div>

                <div className="flex justify-end pt-2">
                  <button
                    type="submit"
                    disabled={actionLoading}
                    className="bg-white hover:bg-neutral-100 text-black px-4 py-2.5 rounded-lg text-xs font-bold transition-all flex items-center justify-center min-w-[150px]"
                  >
                    {actionLoading ? (
                      <div className="w-5 h-5 border-2 border-black border-t-transparent rounded-full animate-spin"></div>
                    ) : (
                      'Generate Cover Letter'
                    )}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* VIEW 3: Detail View for Selected Cover Letter */}
        {viewingLetter && (
          <div className="space-y-4">
            <button
              onClick={() => setViewingLetter(null)}
              className="inline-flex items-center gap-1.5 text-xs text-neutral-400 hover:text-white font-semibold mb-2"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Cover Letters</span>
            </button>

            <div>
              <h1 className="text-4xl font-extrabold text-white tracking-tight">Cover Letter Preview</h1>
              <p className="text-xs text-neutral-500 mt-1">Review and copy your tailored cover letter</p>
            </div>

            <div className="border border-neutral-900 rounded-xl bg-[#09090b] overflow-hidden flex flex-col">
              
              {/* Preview Header */}
              <div className="p-6 border-b border-neutral-900 flex items-center justify-between gap-4 flex-wrap bg-black/30">
                <div>
                  <h3 className="font-bold text-white text-base">
                    {viewingLetter.companyName ? `${viewingLetter.jobTitle} at ${viewingLetter.companyName}` : viewingLetter.jobTitle}
                  </h3>
                  <p className="text-xs text-neutral-500 font-semibold">{formatDate(viewingLetter.createdAt)}</p>
                </div>

                <button
                  onClick={handleCopy}
                  className="inline-flex items-center gap-1.5 border border-neutral-800 bg-[#060608] hover:bg-[#0c0c0e] px-4 py-2 rounded-lg text-xs font-bold transition-all text-white"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4 text-emerald-400" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 text-neutral-400" />
                      <span>Copy Text</span>
                    </>
                  )}
                </button>
              </div>

              {/* Letter Sheet Container */}
              <div className="p-10 bg-[#050507] flex items-center justify-center">
                <div className="bg-white text-neutral-900 p-10 rounded-xl shadow-2xl font-serif max-w-2xl w-full min-h-[500px] leading-relaxed whitespace-pre-wrap select-text text-sm">
                  {viewingLetter.content}
                </div>
              </div>

            </div>
          </div>
        )}

      </main>

      {/* Center Footer Credit */}
      <footer className="border-t border-neutral-900 py-12 bg-black relative z-10 text-center">
        <div className="container mx-auto px-6">
          <div className="text-xs text-neutral-500 font-medium">
            &copy; {new Date().getFullYear()} SensAI. All rights reserved.
          </div>
        </div>
      </footer>

      <ProfileModal isOpen={isProfileOpen} onClose={() => setIsProfileOpen(false)} />
    </div>
  );
};

export default CoverLetterPage;
