import mongoose from 'mongoose';

const questionSchema = new mongoose.Schema({
  question: {
    type: String,
    required: true,
  },
  options: {
    type: [String],
    default: [],
  },
  answer: {
    type: String, // Ideal answer generated by AI
    required: true,
  },
  userAnswer: {
    type: String,
    default: '',
  },
  feedback: {
    type: String, // Feedback on user's answer
    default: '',
  },
  isCorrect: {
    type: Boolean,
    default: false,
  },
});

const interviewSessionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    quizScore: {
      type: Number,
      default: 0,
    },
    category: {
      type: String, // e.g. "Technical", "Behavioral"
      required: true,
    },
    questions: {
      type: [questionSchema],
      default: [],
    },
    improvementTip: {
      type: String,
      default: '',
    },
  },
  {
    timestamps: true,
  }
);

interviewSessionSchema.index({ userId: 1 });

const InterviewSession = mongoose.model('InterviewSession', interviewSessionSchema);
export default InterviewSession;
